### PR TITLE
Sidebar

### PR DESCRIPTION
**Pull request by Proliecan**

### CODE REVIEW

**Comment by Proliecan** [comment]
# The sidebar still needs:

- [ ] List of Lists owned by user (I don't understand how to make that specific API call)
- [ ] Logout-Button functionality
- [ ] User-Icon-Button (should lead to /user)

**Comment by DE38** [comment]
How should the "New List" Button be handled? Should the user be able to create a new list inside the sidebar or be directed to a creation page?

**Comment by Proliecan** [comment]
> How should the "New List" Button be handled? Should the user be able to create a new list inside the sidebar or be directed to a creation page?

I think it would be amazing if the user could create the list right in the taskbar. Maybe change the add button to an input field upon click that is already focussed and allows the user to enter the name of the new list.
Pressing return then creates the list.
The signature color of the list should be assigned at random (we lack a selection field rn).

**Comment by DE38** [comment]
> > How should the "New List" Button be handled? Should the user be able to create a new list inside the sidebar or be directed to a creation page?
> 
> I think it would be amazing if the user could create the list right in the taskbar. Maybe change the add button to an input field upon click that is already focussed and allows the user to enter the name of the new list. Pressing return then creates the list. The signature color of the list should be assigned at random (we lack a selection field rn).

I have tested it and it is technically not possible. The `+landing.server.ts` does not support actions. So a POST action has to be in a `+page.server.ts`. So I would just link to /main with an anchor to the form.

**Comment by Proliecan** [comment]
> > > How should the "New List" Button be handled? Should the user be able to create a new list inside the sidebar or be directed to a creation page?
> > 
> > 
> > I think it would be amazing if the user could create the list right in the taskbar. Maybe change the add button to an input field upon click that is already focussed and allows the user to enter the name of the new list. Pressing return then creates the list. The signature color of the list should be assigned at random (we lack a selection field rn).
> 
> I have tested it and it is technically not possible. The `+landing.server.ts` does not support actions. A POST action has to be in a `+page.server.ts`. So I would just link to /main with an anchor to the form.

Have you tried to put the POST request in the component itself?

**Review by Yadusable — APPROVED** [review]
thanks for the work!

**Pull request merged**
